-- 六模組翻譯鏈：離散圖靈計算 → 連續流場
import FluidTuringLean.M1_Computability
import FluidTuringLean.M2_Interpreter
import FluidTuringLean.M3_Encoding
import FluidTuringLean.M3b_ReversibleTM
import FluidTuringLean.M3c_Bennett
import FluidTuringLean.M3d_BennettTM
import FluidTuringLean.M3e_FixedTM
import FluidTuringLean.M4_Suspension
import FluidTuringLean.M5_ReebInterface
import FluidTuringLean.M6_EulerTuring
import FluidTuringLean.M7_NavierStokes
import FluidTuringLean.M8_FixedMachine
import FluidTuringLean.M9_Undecidability
import FluidTuringLean.M10_BlowupUndecidable
import FluidTuringLean.M11_BlowupODE
import FluidTuringLean.M12_HaltBlowupBridge
import FluidTuringLean.M13_SmoothSwitch
import FluidTuringLean.M14_OrbitFaithful
import FluidTuringLean.M15_UniversalWiring
import FluidTuringLean.M16_TM2Wiring
import FluidTuringLean.M17_TM2Layout
import FluidTuringLean.M18_MtrControl
import FluidTuringLean.M19_MtrEncoder

import FluidTuringLean.M20_FlowCapstone
import FluidTuringLean.M21_MtrConfig
